### ISSUE TITLE
Migrate to pyproject.toml

### ISSUE THREAD

**Issue by VannTen** [thoth-station/aicoe-ci-pulp-upload-example#24]
Translate setup.py into a pyproject.toml file  

/kind feature
/triage accepted
/sig stack-guidance
/good-first-issue
/label hacktoberfest

Parent issue: https://github.com/thoth-station/core/issues/360

**Comment by theyashl** [comment]
Hi @VannTen , I have raised a MR with requested changes! Let me know if any more changes are required..
